spring:
  # 데이터베이스 연결 설정
  datasource: # 여러 DBaaS에서 가져오기
    url: ${DB_URL} # 데이터베이스 URL
    username: ${DB_USER} # 데이터베이스 사용자 이름
    password: ${DB_PASSWORD} # 데이터베이스 비밀번호
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # OSIV 비활성화 (API 서버라면 false 추천)\

  data:
    redis:
      host: ${REDIS_HOST}
      port: 14972
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

mybatis:
  type-aliases-package: com.team5.catdogeats.mybatis

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 1800000

  cookie:
    secure: true
    same-site: Strict
    http-only: true
    max-age: 3600
    domain: null
    path: /

logging:
  level:
    com.team5.catdogeats: debug