server:
  port: 8080 # 충돌 문제 시 수정
spring:
  profiles:
    active: dev
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
  thymeleaf:
    view-names: thymeleaf/*
  web:
    resources:
      static-locations: classpath:/static/
